DROP TRIGGER USER_INSERT;
DROP TRIGGER PROJECT_INSERT;
DROP TRIGGER TASK_INSERT;

DROP TRIGGER USER_UPDATE;
DROP TRIGGER PROJECT_UPDATE;
DROP TRIGGER TASK_UPDATE;

DROP TRIGGER USER_DELETE;
DROP TRIGGER PROJECT_DELETE;
DROP TRIGGER TASK_DELETE;
